export function usage(): string {
  return [
    "Usage: honeycrisp -p <prompt> [--json]",
    "       honeycrisp tools list [options]",
    "       honeycrisp memory <command> [options]",
    "       honeycrisp profile resolve --workspace-root <path> [--profile <path>] --json",
    "",
    "Options:",
    "  -p, --prompt <prompt>  Research request for the agent",
    "  --goal                 Continue the same Pi session until the objective is complete or strictly blocked",
    "  --goal-objective <text> Concise persistent objective separate from the research prompt (implies --goal)",
    "  --success <gate>       Add a success/completion gate",
    "  --stop <gate>          Add a failure or stop gate",
    "  --scope <constraint>   Add a scope constraint",
    "  --evidence <need>      Add an evidence requirement",
    "  --risk <flag>          Add an initial risk flag",
    "  --preference <pref>    Add a user preference",
    "  --mock                 Use the deterministic mock executor (default: real model calls)",
    "  --config <path>        JSON provider/model/effort preference config for real mode",
    "  --collaboration-config <path>  Host-written breakout-room provider and budget configuration",
    "                         Defaults to .honeycrisp/config.json under --workspace-root when present",
    "  --provider <provider>  Override configured/default provider for real mode",
    "  --openai-trusted-access-cyber-risk-acknowledged  Confirm host-recorded OpenAI Trusted Access for Cyber and policy-risk acceptance",
    "  --anthropic-cvp-risk-acknowledged  Confirm host-recorded Anthropic CVP risk acceptance",
    "  --xai-policy-risk-acknowledged  Confirm host-recorded xAI policy-risk acceptance",
    "  --zai-policy-risk-acknowledged  Confirm host-recorded Z.ai policy-risk acceptance",
    "  --model <model>        Override configured/default model for real mode",
    "  --title-model <model>  Generate a session title with this model from the selected provider",
    "  --title-effort <level> Reasoning effort for session title generation (default: medium)",
    "  --executor <kind>      agent (default: agent)",
    "  --max-tokens <n>       Max output tokens for real mode",
    "  --effort <level>       Model effort for real mode: minimal, low, medium, high, xhigh, max",
    "  --reasoning <level>    Alias for --effort",
    "  --tool-execution <m>   Agent tool execution mode: sequential or parallel",
    "  --inspect-root <path>  Allow a local root for read-only inspection",
    "  --inspect-path <path>  Make a local path available for inspection",
    "  --inspect-action <a>   Inspection action: read_text or list",
    "  --inspect-bytes <n>    Max bytes for read_text inspection",
    "  --tool-family <name>   Enable shell, local-inspection, repository-search, file-read, code, analysis, synthesis, storage, or experiment",
    "  --shell-options <path> Harness-wide shell utility policy JSON",
    "  --shell-safety-mode <m> Shell safety: manual_approval, auto_review (default), or danger",
    "  --shell-review-models <json> Provider-to-small-reviewer-model JSON object",
    "                               Defaults: openai-codex=gpt-5.6-luna, anthropic=claude-haiku-4-5, xai=grok-4.3",
    "  --shell-review-effort <level> Small-model review effort (default: medium)",
    "  --memory-type-descriptions <json> Per-memory-type description overrides used by active agents",
    "  --profile <path>       Explicit research profile JSON (overrides the workspace default)",
    "  --resolved-research-profile <path> Exact normalized research profile JSON supplied by a host",
    "  --research-profile-hash <hash> Require the resolved profile to match this SHA-256 hash",
    "  --workflow <id>        Select a workflow from the resolved research profile",
    "  --disable-tool-family <name> Disable a tool family after implicit/default enables",
    "  --profile-tool-family-ceiling <name> Let the active profile request this family within a host ceiling",
    "  --tool-config <path>   Runtime tool preference config (default: .honeycrisp/tools.json)",
    "  --no-default-tool-config Ignore .honeycrisp/tools.json unless --tool-config is provided",
    "  --repo-root <path>     Add a known repository context hint and enable repository.search unless disabled",
    "  --file-read-root <p>   Add a file.read context hint and enable file.read unless disabled",
    "  --source-path <path>   Add a materialized source context path",
    "  --project-note <text>  Add a project/workspace note to compiled context",
    "  --workspace-context <p> JSON workspace context file to merge with CLI hints",
    "  --allowed-side-effect <s> Allow tool side effect: none, read, write, network, process",
    "  --profile-side-effect-ceiling <s> Let the profile request none, read, write, or process within a host ceiling",
    "  --tool-max-calls <n>   Max tool calls for governance",
    "  --tool-runtime-ms <n>  Max runtime per tool call in milliseconds",
    "  --tool-max-files <n>   Max files for file-oriented tools",
    "  --tool-max-bytes <n>   Max bytes for file-oriented tools",
    "  --tool-max-tokens <n>  Max tool output tokens",
    "  --allow-mcp-server <s> Allow an MCP server name in runtime config",
    "  --mcp-config <path>    JSON MCP stdio server config",
    "  --mcp-timeout-ms <n>   MCP request timeout in milliseconds",
    "  --experiment-config <p> JSON allowlisted experiment config",
    "  --skill-dir <path>     Load local skills from child directories containing SKILL.md",
    "  --skill <id>           Request a loaded skill by id",
    "  --capture <path>       Write a local flow-capture JSON artifact",
    "  --session-id <id>     Stable provider affinity ID for this research session",
    "  --resume-capture <p>  Resume compatible model context from a prior capture",
    "  --resume-fallback-prompt <text>  Prompt used when prior state is unavailable",
    "  --resume-fallback-prompt-file <p> Read that fallback prompt from a UTF-8 file",
    "  --event-stream         Write prefixed live JSON events to stdout",
    "  --control-stream       Read host control JSONL from stdin",
    "  --websocket-transport  Host an authenticated loopback WebSocket for live events and controls",
    "  --workspace-root <p>   Workspace root for durable runtime memory",
    "  --json                 Print the initialized run as JSON",
    "  -h, --help             Show help",
    "  -v, --version          Show version",
    "",
    "Memory commands:",
    "  memory state                     Summarize durable knowledge",
    "  memory list                      List durable knowledge nodes",
    "  memory search <query>            Search durable knowledge nodes",
    "  memory get <node-id>             Show one node and its evidence",
    "  memory save <type> <title>       Add or refine a node",
    "  memory correct <node-id>         Correct a node by revision",
    "  memory link <from> <to> <rel>    Link two nodes",
    "",
    "Memory options:",
    "  --workspace-root <path>  Workspace root containing .honeycrisp memory",
    "  --type <type>           Filter nodes; with correct, reclassify one node",
    "  --status <status>       Filter or set node status",
    "  --tag <tag>             Filter or add a tag (repeatable)",
    "  --asset <asset-id>      Filter or add an asset link (repeatable)",
    "  --summary <text>        Set a concise summary or relationship note",
    "  --body <text>           Set supporting detail",
    "  --confidence <0..1>     Set confidence",
    "  --expected-revision <n> Required for exact correction",
    "  --limit <n>             Limit returned nodes",
    "  --json                  Print JSON",
    "",
    "Profile commands:",
    "  profile resolve                  Resolve and normalize the active research profile",
    "",
    "Profile options:",
    "  --workspace-root <path>  Workspace root used for .honeycrisp/profile.json discovery",
    "  --profile <path>         Explicit research profile JSON (highest precedence)",
    "  --json                   Print the versioned profile catalog envelope",
    "",
    "Model commands:",
    "  models list [provider]          List Pi models and supported effort levels",
    "",
    "Tool debug commands:",
    "  tools list                       Show configured tools, MCP allowlist, and selected skills",
    "  tools config show                Show project runtime tool preferences",
    "  config show                      Show project model preference and authorization status",
    "  config set <field> <value>       Set provider, model, or effort preference",
  ].join("\n");
}
